#!/usr/bin/env bash
# src-v6/bmad-bam-platform/9-infrastructure/bmad-bam-finalize/scripts/post-install.sh
#
# Activation finalizer for bmad-bam-platform (Path B per spec §7.6).
# Invoked by the bmad-bam-finalize skill after `bmad install bmad-bam-platform`.
# Skill-local script per BMM convention (each skill is self-contained;
# no module-root scripts/ dir; see v0.8 spec §6.1).
# Generates {output_folder}/project-context.md in the host project,
# containing a BAM_LOAD_VERIFY_<uuid> sentinel token. Idempotent + atomic.
#
# Location convention (BMM-aligned, v0.7 spec §7.6):
#   - File lives in BMAD's {output_folder} (default _bmad-output/), outside
#     _bmad/<module-code>/. This survives BMAD's install-time
#     fs.remove(targetPath) wipe; aligns with BMM's bmad-generate-project-context
#     which also writes to {output_folder}/project-context.md.
#   - Filename `project-context.md` keeps BAM's content separate from
#     BMM's user-generated `project-context.md` (no collision; both load via
#     universal-glob).
#
# Usage: post-install.sh <project-root>

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <project-root>" >&2
    exit 64
fi

PROJECT_ROOT="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SENTINEL_PY="$SCRIPT_DIR/generate-sentinel.py"

if [ ! -d "$PROJECT_ROOT" ]; then
    echo "ERROR: project root '$PROJECT_ROOT' does not exist" >&2
    exit 66
fi

if [ ! -f "$PROJECT_ROOT/_bmad/config.toml" ]; then
    echo "ERROR: '$PROJECT_ROOT' is not a BMAD project (missing _bmad/config.toml)" >&2
    exit 66
fi

# Python 3.11+ pre-check (Task 0 risk #4). BAM's smoke-test workflow invokes
# BMAD's resolve_customization.py which uses stdlib `tomllib` (3.11+). Failing
# here gives a clear error before later steps confuse the user with a
# missing-module trace from inside the resolver.
if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 not found on PATH; BAM requires Python 3.11+ for the BMAD customize resolver" >&2
    exit 75
fi
PY_MAJOR="$(python3 -c 'import sys; print(sys.version_info[0])' 2>/dev/null || echo 0)"
PY_MINOR="$(python3 -c 'import sys; print(sys.version_info[1])' 2>/dev/null || echo 0)"
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 11 ]; }; then
    echo "ERROR: python3 is $PY_MAJOR.$PY_MINOR; BAM requires Python >= 3.11" >&2
    echo "       (BMAD's resolve_customization.py uses stdlib 'tomllib', new in 3.11)" >&2
    exit 75
fi

# Resolve {output_folder} from _bmad/config.toml. Ports BMM's logic at
# external/bmad-method/tools/installer/core/installer.js:1465-1511 to bash.
# Reads `output_folder = ...` (top-level or under any section); strips a
# {project-root}/ prefix if present; defaults to `_bmad-output` if absent.
resolve_output_folder() {
    local project_root="$1"
    local config="$project_root/_bmad/config.toml"
    if [ ! -f "$config" ]; then
        echo "_bmad-output"
        return
    fi
    local value
    # Strip comments + whitespace; match `output_folder = "..."` or
    # `output_folder = ...`. The grep tolerates surrounding spaces; sed
    # extracts the value (handles quoted and unquoted forms).
    value="$(grep -E '^[[:space:]]*output_folder[[:space:]]*=' "$config" \
        | head -1 \
        | sed -E 's/^[[:space:]]*output_folder[[:space:]]*=[[:space:]]*"?([^"#]+)"?.*/\1/' \
        | sed -E 's/[[:space:]]+$//')"
    # Strip {project-root}/ prefix if present (matches BMM resolution)
    value="${value#\{project-root\}/}"
    value="${value#/}"
    echo "${value:-_bmad-output}"
}

OUTPUT_FOLDER_REL="$(resolve_output_folder "$PROJECT_ROOT")"
OUTPUT_FOLDER="$PROJECT_ROOT/$OUTPUT_FOLDER_REL"

# Generate sentinel token
if [ ! -x "$SENTINEL_PY" ]; then
    echo "ERROR: sentinel generator not executable at $SENTINEL_PY" >&2
    exit 73
fi
SENTINEL="$(python3 "$SENTINEL_PY")"

# Target directory + file — BMM-aligned: {output_folder}/project-context.md.
# Survives BMAD installer's fs.remove(targetPath) because {output_folder} is outside
# _bmad/<module-code>/.
TARGET_DIR="$OUTPUT_FOLDER/bbp"
TARGET_FILE="$TARGET_DIR/project-context.md"

mkdir -p "$TARGET_DIR"
TMP_FILE="$(mktemp "${TARGET_DIR}/.bam-platform.XXXXXX.tmp")"

# Write to temp file
cat > "$TMP_FILE" <<EOF
<!-- Generated by bmad-bam-platform post-install.sh -->
<!-- Do not edit by hand; regenerated on every \`bmad run bmad-bam-finalize\` -->

# BAM v6 Platform Module — Project Context

This file is the bmad-bam-platform module's project-context contribution.
BMAD core skills auto-load it at activation via the universal-glob pattern
(\`file:{project-root}/**/project-context.md\`) declared in each skill's
\`customize.toml: persistent_facts\` (or \`workflow.persistent_facts\` for
workflow-namespace skills).

Location convention (BMM-aligned, v0.7 spec §7.6): file lives in BMAD's
\`{output_folder}/\` (default \`_bmad-output/\`), outside
\`_bmad/<module-code>/\`. This survives BMAD's install-time wipe.

## Activation sentinel

$SENTINEL

If a BMAD skill's loaded context contains the token above, the universal-glob
activation mechanism is working end-to-end. (Headlessly verified by the
smoke-test workflow; LLM-side ratification: \`tests/p2/PLAN-C-RATIFICATION.md\`.)

## Installed personas

- **Atlas** (🏛️ Platform Architect) — multi-tenant SaaS platform architect.
  Holds up the platform sky: RLS strategy, modular monolith decomposition,
  tenant tier modeling, FinOps. Speaks like a structural engineer at a
  whiteboard. Owns QG-F1, QG-M1, QG-M2, QG-DA1.

## Installed skills

- **bmad-bam-finalize** — this activation finalizer (re-runnable).
- **bmad-bam-smoke-test** — Wave 0 activation-mechanism verification.
- **bmad-bam-design-tenancy-model** — first BAM workflow (P2.1). Produces
  \`docs/architecture/tenancy-model.md\` + ADR + partial QG-M2 evidence.
  Invoke via \`bmad run bmad-bam-design-tenancy-model\`.

## Module status

Module installed via Path B (manual finalize) per spec §7.6 / P2.1 Task 0.
Re-run \`bmad run bmad-bam-finalize\` after any \`bmad install bmad-bam-platform\`
upgrade to refresh this sentinel.

EOF

# Atomic rename (same filesystem since TMP_FILE is in TARGET_DIR)
mv -f "$TMP_FILE" "$TARGET_FILE"

# Log install
LOG_DIR="$PROJECT_ROOT/_bmad/bam/install-logs"
mkdir -p "$LOG_DIR"
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] post-install ran; sentinel=$SENTINEL; output_folder=$OUTPUT_FOLDER_REL; target=$TARGET_FILE" >> "$LOG_DIR/platform-install.log"

# Seed Atlas's sidecar memory ADR index (idempotent — only writes if absent).
# Downstream workflows (bmad-bam-design-tenancy-model step-06) append ADRs to
# this file. In a fresh project the directory + index don't exist; append-only
# semantics on a missing file are undefined.
ADR_DIR="$PROJECT_ROOT/_bmad/_memory/atlas/architecture-decisions"
INDEX="$ADR_DIR/INDEX.md"
mkdir -p "$ADR_DIR"
if [ ! -f "$INDEX" ]; then
    cat > "$INDEX" <<'INDEX_EOF'
# Atlas — Architecture Decisions Index

| ID | Title | Status | Date |
|---|---|---|---|
INDEX_EOF
fi

echo "$SENTINEL"
