#!/usr/bin/env bash
# src-v6/bmad-bam-platform/scripts/post-install.sh
#
# Activation finalizer for bmad-bam-platform (Path B per spec §7.6).
# Invoked by the bmad-bam-finalize skill after `bmad install bmad-bam-platform`.
# Generates _bmad/bam-activation/platform/project-context.md in the host project,
# containing a BAM_LOAD_VERIFY_<uuid> sentinel token. Idempotent + atomic.
#
# Usage: post-install.sh <project-root>

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <project-root>" >&2
    exit 64
fi

PROJECT_ROOT="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SENTINEL_PY="$SCRIPT_DIR/generate-sentinel.py"

if [ ! -d "$PROJECT_ROOT" ]; then
    echo "ERROR: project root '$PROJECT_ROOT' does not exist" >&2
    exit 66
fi

if [ ! -f "$PROJECT_ROOT/_bmad/config.toml" ]; then
    echo "ERROR: '$PROJECT_ROOT' is not a BMAD project (missing _bmad/config.toml)" >&2
    exit 66
fi

# Python 3.11+ pre-check (Task 0 risk #4). BAM's smoke-test workflow invokes
# BMAD's resolve_customization.py which uses stdlib `tomllib` (3.11+). Failing
# here gives a clear error before later steps confuse the user with a
# missing-module trace from inside the resolver.
if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 not found on PATH; BAM requires Python 3.11+ for the BMAD customize resolver" >&2
    exit 75
fi
PY_MAJOR="$(python3 -c 'import sys; print(sys.version_info[0])' 2>/dev/null || echo 0)"
PY_MINOR="$(python3 -c 'import sys; print(sys.version_info[1])' 2>/dev/null || echo 0)"
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 11 ]; }; then
    echo "ERROR: python3 is $PY_MAJOR.$PY_MINOR; BAM requires Python >= 3.11" >&2
    echo "       (BMAD's resolve_customization.py uses stdlib 'tomllib', new in 3.11)" >&2
    exit 75
fi

# Generate sentinel token
if [ ! -x "$SENTINEL_PY" ]; then
    echo "ERROR: sentinel generator not executable at $SENTINEL_PY" >&2
    exit 73
fi
SENTINEL="$(python3 "$SENTINEL_PY")"

# Target directory + file
TARGET_DIR="$PROJECT_ROOT/_bmad/bam-activation/platform"
TARGET_FILE="$TARGET_DIR/project-context.md"
TMP_FILE="$(mktemp "${TARGET_DIR}.XXXXXX.tmp" 2>/dev/null || mktemp /tmp/bam-platform.XXXXXX.tmp)"

mkdir -p "$TARGET_DIR"

# Write to temp file
cat > "$TMP_FILE" <<EOF
<!-- Generated by bmad-bam-platform post-install.sh -->
<!-- Do not edit by hand; regenerated on every install -->

# BAM v6 Platform Module — Project Context

This file is the BAM v6 activation sentinel for the bmad-bam-platform module.
BMAD core skills auto-load it at activation via the universal-glob pattern
(\`file:{project-root}/**/project-context.md\`) declared in each skill's
\`customize.toml: persistent_facts\`.

## Activation sentinel

$SENTINEL

If a BMAD skill's loaded context contains the token above, the universal-glob
activation mechanism is working end-to-end. (Headlessly verified during Wave 0;
LLM-side ratification: \`tests/p2/PLAN-C-RATIFICATION.md\`.)

## Installed personas

- **Atlas** (🏛️ Platform Architect) — multi-tenant SaaS platform architect.
  Holds up the platform sky: RLS strategy, modular monolith decomposition,
  tenant tier modeling, FinOps. Speaks like a structural engineer at a
  whiteboard. Owns QG-F1, QG-M1, QG-M2, QG-DA1.

## Installed skills

- **bmad-bam-finalize** — this activation finalizer (re-runnable).
- **bmad-bam-smoke-test** — Wave 0 activation-mechanism verification.
- **bmad-bam-design-tenancy-model** — first BAM workflow (P2.1). Produces
  \`docs/architecture/tenancy-model.md\` + ADR + partial QG-M2 evidence.
  Invoke via \`bmad run bmad-bam-design-tenancy-model\`.

## Module status

Module installed via Path B (manual finalize) per spec §7.6 / P2.1 Task 0.
Re-run \`bmad run bmad-bam-finalize\` after any \`bmad install bmad-bam-platform\`
upgrade to refresh this sentinel.

EOF

# Atomic rename
mv -f "$TMP_FILE" "$TARGET_FILE"

# Log install
LOG_DIR="$PROJECT_ROOT/_bmad/bam/install-logs"
mkdir -p "$LOG_DIR"
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] post-install ran; sentinel=$SENTINEL; target=$TARGET_FILE" >> "$LOG_DIR/platform-install.log"

echo "$SENTINEL"
