#!/usr/bin/env bash
# src-v6/bmad-bam-platform/scripts/post-install.sh
#
# Wave 0 post-install hook.
# Generates _bmad/platform/project-context.md in the host project, containing
# a BAM_LOAD_VERIFY_<uuid> sentinel token. Idempotent + atomic.
#
# Usage: post-install.sh <project-root>

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <project-root>" >&2
    exit 64
fi

PROJECT_ROOT="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SENTINEL_PY="$SCRIPT_DIR/generate-sentinel.py"

if [ ! -d "$PROJECT_ROOT" ]; then
    echo "ERROR: project root '$PROJECT_ROOT' does not exist" >&2
    exit 66
fi

if [ ! -f "$PROJECT_ROOT/_bmad/config.toml" ]; then
    echo "ERROR: '$PROJECT_ROOT' is not a BMAD project (missing _bmad/config.toml)" >&2
    exit 66
fi

# Generate sentinel token
if [ ! -x "$SENTINEL_PY" ]; then
    echo "ERROR: sentinel generator not executable at $SENTINEL_PY" >&2
    exit 73
fi
SENTINEL="$(python3 "$SENTINEL_PY")"

# Target directory + file
TARGET_DIR="$PROJECT_ROOT/_bmad/platform"
TARGET_FILE="$TARGET_DIR/project-context.md"
TMP_FILE="$(mktemp "${TARGET_DIR}.XXXXXX.tmp" 2>/dev/null || mktemp /tmp/bam-platform.XXXXXX.tmp)"

mkdir -p "$TARGET_DIR"

# Write to temp file
cat > "$TMP_FILE" <<EOF
<!-- Generated by bmad-bam-platform post-install.sh -->
<!-- Do not edit by hand; regenerated on every install -->

# BAM v6 Platform Module — Project Context

## Wave 0 Sentinel

$SENTINEL

If you see the token above in a BMAD skill's loaded context, the universal-glob mechanism (Plan A) is working.

## Installed personas

- Atlas (🏛️ Platform Architect) — stub in Wave 0; full persona in P2.

## Wave 0 status

Module installed in Wave 0 smoke-test mode. Run the smoke-test workflow to determine which activation plan applies.

EOF

# Atomic rename
mv -f "$TMP_FILE" "$TARGET_FILE"

# Log install
LOG_DIR="$PROJECT_ROOT/_bmad/bam/install-logs"
mkdir -p "$LOG_DIR"
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] post-install ran; sentinel=$SENTINEL; target=$TARGET_FILE" >> "$LOG_DIR/platform-install.log"

echo "$SENTINEL"
