/**
 * E2E tests for Foundation Chain workflows
 * Validates artifacts generated by tenant-model-isolation and related workflows
 *
 * These tests run against the installed bmad-with-wds-bam directory
 * to verify complete workflow execution produces correct artifacts.
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

// Paths relative to bmad-bam source (for running from source)
const SRC_DIR = path.join(__dirname, '..', '..', 'src');
const WORKFLOWS_DIR = path.join(SRC_DIR, 'workflows');
const DATA_DIR = path.join(SRC_DIR, 'data');

// Installed directory paths (for E2E validation against installed artifacts)
// Note: Tests can run in two modes:
// 1. Source mode: Validates workflow structure in bmad-bam/src
// 2. Install mode: Validates artifacts in bmad-with-wds-bam/_bmad-output
const INSTALL_DIR = path.join(__dirname, '..', '..', '..', 'bmad-with-wds-bam');
const OUTPUT_DIR = path.join(INSTALL_DIR, '_bmad-output', 'planning-artifacts');
const BAM_CONFIG_PATH = path.join(INSTALL_DIR, '_bmad', 'bam', 'config.yaml');

describe('E2E Foundation Chain - Source Structure', () => {
  describe('Tenant Model Isolation Workflow Structure', () => {
    // Note: tenant-model-isolation is a FLAT workflow (not nested), so uses full name
    const workflowPath = path.join(WORKFLOWS_DIR, 'bmad-bam-tenant-model-isolation');

    test('workflow directory exists', () => {
      expect(fs.existsSync(workflowPath)).toBe(true);
    });

    test('has required workflow files', () => {
      const requiredFiles = [
        'bmad-skill-manifest.yaml',
        'SKILL.md',
        'workflow.md'
      ];

      requiredFiles.forEach(file => {
        const filePath = path.join(workflowPath, file);
        expect(fs.existsSync(filePath)).toBe(true);
      });
    });

    test('has step files directory', () => {
      const stepsPath = path.join(workflowPath, 'steps');
      expect(fs.existsSync(stepsPath)).toBe(true);
    });

    test('has Create mode steps (step-0N-c-*)', () => {
      const stepsPath = path.join(workflowPath, 'steps');
      const steps = fs.readdirSync(stepsPath);

      const createSteps = steps.filter(s => /^step-0[1-9]-c-/.test(s));
      expect(createSteps.length).toBeGreaterThanOrEqual(1);
    });

    test('has Edit mode steps (step-1N-e-*)', () => {
      const stepsPath = path.join(workflowPath, 'steps');
      const steps = fs.readdirSync(stepsPath);

      const editSteps = steps.filter(s => /^step-1[0-9]-e-/.test(s));
      expect(editSteps.length).toBeGreaterThanOrEqual(1);
    });

    test('has Validate mode steps (step-2N-v-*)', () => {
      const stepsPath = path.join(workflowPath, 'steps');
      const steps = fs.readdirSync(stepsPath);

      const validateSteps = steps.filter(s => /^step-2[0-9]-v-/.test(s));
      expect(validateSteps.length).toBeGreaterThanOrEqual(1);
    });

    test('manifest has correct workflow name', () => {
      const manifestPath = path.join(workflowPath, 'bmad-skill-manifest.yaml');
      const manifest = yaml.load(fs.readFileSync(manifestPath, 'utf-8'));

      expect(manifest.name).toBe('bmad-bam-tenant-model-isolation');
      expect(manifest.type).toBe('workflow');
      expect(manifest.module).toBe('bam');
    });

    test('workflow.md defines all three modes', () => {
      const workflowMd = fs.readFileSync(
        path.join(workflowPath, 'workflow.md'),
        'utf-8'
      );

      expect(workflowMd).toContain('Create');
      expect(workflowMd).toContain('Edit');
      expect(workflowMd).toContain('Validate');
    });
  });

  describe('Create Master Architecture Workflow Structure', () => {
    const workflowPath = path.join(WORKFLOWS_DIR, 'foundation', 'create-master-architecture');

    test('workflow directory exists', () => {
      expect(fs.existsSync(workflowPath)).toBe(true);
    });

    test('has required workflow files', () => {
      const requiredFiles = [
        'bmad-skill-manifest.yaml',
        'SKILL.md',
        'workflow.md'
      ];

      requiredFiles.forEach(file => {
        const filePath = path.join(workflowPath, file);
        expect(fs.existsSync(filePath)).toBe(true);
      });
    });

    test('manifest references QG-F1 gate', () => {
      const skillMd = fs.readFileSync(
        path.join(workflowPath, 'SKILL.md'),
        'utf-8'
      );

      expect(skillMd).toContain('QG-F1');
    });
  });

  describe('Validate Foundation Workflow Structure', () => {
    const workflowPath = path.join(WORKFLOWS_DIR, 'foundation', 'validate-foundation');

    test('workflow directory exists', () => {
      expect(fs.existsSync(workflowPath)).toBe(true);
    });

    test('has validation step files', () => {
      const stepsPath = path.join(workflowPath, 'steps');
      if (fs.existsSync(stepsPath)) {
        const steps = fs.readdirSync(stepsPath);
        const validateSteps = steps.filter(s => /^step-2[0-9]-v-/.test(s));
        expect(validateSteps.length).toBeGreaterThanOrEqual(1);
      }
    });
  });
});

describe('E2E Foundation Chain - Installed Artifacts', () => {
  // Skip these tests if installed directory doesn't exist
  const installExists = fs.existsSync(INSTALL_DIR);
  const configExists = installExists && fs.existsSync(BAM_CONFIG_PATH);

  const describeFn = (installExists && configExists) ? describe : describe.skip;

  describeFn('BAM Configuration', () => {
    test('config.yaml exists and has correct tenant_model', () => {
      const config = yaml.load(fs.readFileSync(BAM_CONFIG_PATH, 'utf-8'));
      expect(config.tenant_model).toBe('row-level-security');
    });

    test('config.yaml has correct ai_runtime', () => {
      const config = yaml.load(fs.readFileSync(BAM_CONFIG_PATH, 'utf-8'));
      expect(config.ai_runtime).toBe('langgraph');
    });

    test('config.yaml has output_folder configured', () => {
      const config = yaml.load(fs.readFileSync(BAM_CONFIG_PATH, 'utf-8'));
      expect(config.output_folder).toBeDefined();
    });
  });

  const outputExists = installExists && fs.existsSync(OUTPUT_DIR);
  const artifactDescribeFn = outputExists ? describe : describe.skip;

  artifactDescribeFn('E2E-F1: Tenant Model Isolation Artifacts', () => {
    const tenantModelPath = path.join(OUTPUT_DIR, 'architecture', 'tenant-model.md');
    const isolationMatrixPath = path.join(OUTPUT_DIR, 'architecture', 'tenant-isolation-matrix.md');

    test('tenant-model.md artifact exists', () => {
      expect(fs.existsSync(tenantModelPath)).toBe(true);
    });

    test('tenant-model.md has YAML frontmatter', () => {
      const content = fs.readFileSync(tenantModelPath, 'utf-8');
      expect(content.startsWith('---')).toBe(true);

      // Extract frontmatter
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
      expect(frontmatterMatch).not.toBeNull();

      const frontmatter = yaml.load(frontmatterMatch[1]);
      expect(frontmatter.name).toBeDefined();
      expect(frontmatter.type).toBe('architecture');
    });

    test('tenant-model.md has stepsCompleted tracking', () => {
      const content = fs.readFileSync(tenantModelPath, 'utf-8');
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
      const frontmatter = yaml.load(frontmatterMatch[1]);

      expect(frontmatter.stepsCompleted).toBeDefined();
      expect(Array.isArray(frontmatter.stepsCompleted)).toBe(true);
      expect(frontmatter.stepsCompleted.length).toBeGreaterThanOrEqual(5);
    });

    test('tenant-model.md has Tenant Entity Structure', () => {
      const content = fs.readFileSync(tenantModelPath, 'utf-8');
      expect(content).toContain('Tenant Entity');
    });

    test('tenant-model.md has tier matrix (FREE/PRO/ENTERPRISE)', () => {
      const content = fs.readFileSync(tenantModelPath, 'utf-8');
      expect(content).toContain('FREE');
      expect(content).toContain('PRO');
      expect(content).toContain('ENTERPRISE');
    });

    test('tenant-model.md has lifecycle states', () => {
      const content = fs.readFileSync(tenantModelPath, 'utf-8');
      expect(content).toContain('PROVISIONING');
      expect(content).toContain('ACTIVE');
      expect(content).toContain('SUSPENDED');
    });

    test('tenant-model.md has context propagation design', () => {
      const content = fs.readFileSync(tenantModelPath, 'utf-8');
      expect(content).toContain('Context Propagation');
    });

    test('tenant-model.md has QG-M2 checklist reference', () => {
      const content = fs.readFileSync(tenantModelPath, 'utf-8');
      expect(content).toContain('QG-M2');
    });

    test('tenant-isolation-matrix.md artifact exists', () => {
      expect(fs.existsSync(isolationMatrixPath)).toBe(true);
    });

    test('tenant-isolation-matrix.md has YAML frontmatter', () => {
      const content = fs.readFileSync(isolationMatrixPath, 'utf-8');
      expect(content.startsWith('---')).toBe(true);
    });

    test('tenant-isolation-matrix.md has RLS patterns', () => {
      const content = fs.readFileSync(isolationMatrixPath, 'utf-8');
      expect(content).toContain('RLS');
      expect(content).toContain('tenant_id');
    });

    test('tenant-isolation-matrix.md covers all asset categories', () => {
      const content = fs.readFileSync(isolationMatrixPath, 'utf-8');

      // Core asset categories that must be covered
      const requiredCategories = [
        'Database',
        'Cache',
        'Storage',
        'AI'
      ];

      requiredCategories.forEach(category => {
        expect(content).toContain(category);
      });
    });

    test('tenant-isolation-matrix.md has verification tests defined', () => {
      const content = fs.readFileSync(isolationMatrixPath, 'utf-8');
      expect(content).toContain('Verification');
    });

    test('tenant-isolation-matrix.md has context propagation matrix', () => {
      const content = fs.readFileSync(isolationMatrixPath, 'utf-8');
      expect(content).toContain('Context Propagation');
    });
  });
});

describe('E2E Foundation Chain - Template Structure', () => {
  const templatesDir = path.join(DATA_DIR, 'templates');

  test('tenant-model-template.md exists', () => {
    const templatePath = path.join(templatesDir, 'tenant-model-template.md');
    expect(fs.existsSync(templatePath)).toBe(true);
  });

  test('tenant-isolation-matrix.md template exists', () => {
    // Check various possible names
    const possibleNames = [
      'tenant-isolation-matrix.md',
      'tenant-isolation-matrix-template.md',
      'isolation-matrix-template.md'
    ];

    const exists = possibleNames.some(name =>
      fs.existsSync(path.join(templatesDir, name))
    );

    expect(exists).toBe(true);
  });

  test('master-architecture-template.md exists', () => {
    const templatePath = path.join(templatesDir, 'master-architecture-template.md');
    expect(fs.existsSync(templatePath)).toBe(true);
  });
});

describe('E2E Foundation Chain - Checklist Structure', () => {
  const checklistsDir = path.join(DATA_DIR, 'checklists');

  test('qg-f1-foundation.md (QG-F1) checklist exists', () => {
    const checklistPath = path.join(checklistsDir, 'qg-f1-foundation.md');
    expect(fs.existsSync(checklistPath)).toBe(true);
  });

  test('qg-m2-tenant-isolation.md (QG-M2) checklist exists', () => {
    const checklistPath = path.join(checklistsDir, 'qg-m2-tenant-isolation.md');
    expect(fs.existsSync(checklistPath)).toBe(true);
  });

  test('QG-F1 checklist has checkbox format', () => {
    const checklistPath = path.join(checklistsDir, 'qg-f1-foundation.md');
    const content = fs.readFileSync(checklistPath, 'utf-8');

    // Should have checkbox items
    expect(content).toMatch(/- \[[ x]\]/);
  });

  test('QG-M2 checklist has CRITICAL markers', () => {
    const checklistPath = path.join(checklistsDir, 'qg-m2-tenant-isolation.md');
    const content = fs.readFileSync(checklistPath, 'utf-8');

    // Should have CRITICAL items marked
    expect(content).toContain('CRITICAL');
  });
});

describe('E2E Foundation Chain - Pattern Registry', () => {
  test('bam-patterns.csv has tenant-isolation category', () => {
    const csvPath = path.join(DATA_DIR, 'bam-patterns.csv');
    const content = fs.readFileSync(csvPath, 'utf-8');

    expect(content).toContain('tenant-isolation');
  });

  test('tenant-models.csv has row-level-security', () => {
    const csvPath = path.join(DATA_DIR, 'tenant-models.csv');
    const content = fs.readFileSync(csvPath, 'utf-8');

    expect(content).toContain('row-level-security');
  });

  test('quality-gates.csv has QG-F1 and QG-M2', () => {
    const csvPath = path.join(DATA_DIR, 'quality-gates.csv');
    const content = fs.readFileSync(csvPath, 'utf-8');

    expect(content).toContain('QG-F1');
    expect(content).toContain('QG-M2');
  });
});

describe('E2E Foundation Chain - Cross-Module Integration', () => {
  test('tenant-model-isolation workflow references correct templates', () => {
    const workflowPath = path.join(WORKFLOWS_DIR, 'bmad-bam-tenant-model-isolation');
    const stepsPath = path.join(workflowPath, 'steps');

    if (fs.existsSync(stepsPath)) {
      const steps = fs.readdirSync(stepsPath);
      let hasTemplateRef = false;

      steps.forEach(step => {
        const content = fs.readFileSync(path.join(stepsPath, step), 'utf-8');
        if (content.includes('template') || content.includes('Template')) {
          hasTemplateRef = true;
        }
      });

      expect(hasTemplateRef).toBe(true);
    }
  });

  test('workflow step files reference pattern registry', () => {
    const workflowPath = path.join(WORKFLOWS_DIR, 'bmad-bam-tenant-model-isolation');
    const stepsPath = path.join(workflowPath, 'steps');

    if (fs.existsSync(stepsPath)) {
      const steps = fs.readdirSync(stepsPath);
      let hasPatternRef = false;

      steps.forEach(step => {
        const content = fs.readFileSync(path.join(stepsPath, step), 'utf-8');
        if (content.includes('Load patterns') || content.includes('bam-patterns.csv')) {
          hasPatternRef = true;
        }
      });

      expect(hasPatternRef).toBe(true);
    }
  });
});
